apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: selecciongalicia
  name: selecciongaliciadeploy
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: selecciongalicia
  template:
    metadata:
      labels:
        app: selecciongalicia
    spec:
      containers:
      - image: tkd157/selecciongalicia:latest
        imagePullPolicy: Always
        name: selecciongalicia
---
apiVersion: v1
kind: Service
metadata:
  name: selecciongalicia
  namespace: default
spec:
  ports:
  - nodePort: 30377
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: selecciongalicia
  type: NodePort
